import { createAction } from '@reduxjs/toolkit';
import { STATE_REDUCER_KEY } from './constants';

export const ACTION_TYPES = {

  FETCH_COUNTRY: `${STATE_REDUCER_KEY}/FETCH_COUNTRY`,
  FETCH_COUNTRY_REQUEST: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_REQUEST`,
  FETCH_COUNTRY_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_SUCCESS`,
  FETCH_COUNTRY_FAILURE: `${STATE_REDUCER_KEY}/FETCH_COUNTRY_FAILURE`,

};


export const fetchCountry = createAction(ACTION_TYPES.FETCH_COUNTRY);
